services:
  landing-page:
    build:
      context: ./src/landing-page
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.landing-page.rule=Host(`localhost`)"
      - "traefik.http.services.landing-page.loadbalancer.server.port=80"

  api:
    image: ghcr.io/larsgjobloop/memoryservice:main-b5b9e47
    labels:
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      - "traefik.http.services.landing-page.loadbalancer.server.port=8080"

  # Platform servicess
  # These you often outsource to platforms

  # Ingress Service (aka a Gate)
  ingress:
    image: traefik:v3.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # PosgreSQL is a Database Management System DBMS
  # This is the first thing you want to outsource
  database:
    image: postgres:18
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: memories
    # Expose the port so we can debug it
    # with a local client
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
